type Query {
    greeting: [Job1]!
    job(id: ID!): Job  # Query with an argument
    jobs: [Job]
    company(id:ID!): Company #Query with an argument   
}
# to write to databse in graphql we use Mutation
type Mutation {
    # way1 to send input variables in graphql
    # createJobM(title: String! , description: String): Job 
    
    # way2 to send input variables in graphql
    createJobM(input: CreateJobInput!): Job
    deleteJobM(id: ID!): Job
    updateJobM(input: UpdateJobInput!):Job
}

type Job1 {
    name: String
}
type Company {
    id: ID!
    name: String
    description: String
    jobs: [Job!]!
}
type Job {
    id:ID
    """ This is documentation comment for date"""
    date: String!
    """ This is documentation comment for title"""
    title: String
    """ This is documentation comment for desc"""
    description: String

    company: Company!
}

input CreateJobInput {
    title: String!
    description: String
}

input UpdateJobInput {
    id:ID!
    title:String!
    description:String
}
